---
- name: Converge
  hosts: all
  become: true
  vars:
    mongodb_net_bindip: 0.0.0.0
    mongodb_storage_dbpath: /var/lib/mongodb/
    mongodb_replication_replset: "rs0"

  pre_tasks:
    # - name: Print facts
    #   debug:
    #     var: ansible_facts

    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

    - name: Fill /etc/hosts with hosts entry
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_host'] }}  {{ item }}"
      loop: "{{ groups['mongodb_instances'] }}"

    - name: Test hosts
      ansible.builtin.debug:
        msg: "{{ hostvars[item]['ip_adr'] }}  {{ item }}"
      loop: "{{ groups['mongodb_instances'] }}"

  roles:
    - role: mongodb_install
    - {role: mongodb_replicaset, when: groups.mongodb_instances.index(inventory_hostname) == 0}
