---
- name: Mongodb restart
  ansible.builtin.service:
    name: "{{ mongodb_daemon_name }}"
    state: restarted
  when: mongodb_manage_service | bool

- name: Wait when mongodb is started
  ansible.builtin.wait_for:
    host: "{{ item }}"
    port: "{{ mongodb_net_port }}"
    timeout: 120
  loop: "{{ mongodb_net_bindip.split(',') | map('replace', '0.0.0.0', '127.0.0.1') | list }}"

- name: Wait when mongodb is started on localhost
  ansible.builtin.wait_for:
    host: "127.0.0.1"
    port: "{{ mongodb_net_port }}"
    delay: 5
    timeout: 120
