---
- name: Converge
  hosts: all
  become: true
  vars:
    mongodb_net_bindip: 0.0.0.0
    mongodb_storage_dbpath: /var/lib/mongodb/
    mongodb_replication_replset: "rs0"
    admin_password: admin
    user_password: user

  roles:
    - {role: mongodb_install}
    - {role: mongodb_replicaset, when: groups.mongodb_instances.index(inventory_hostname) == 0}
