---
- name: Converge
  hosts: all
  become: true
  vars:
    mongodb_net_bindip: 0.0.0.0
    mongodb_storage_dbpath: /var/lib/mongodb/
    mongodb_replication_replset: "rs0"
    admin_password: admin
    user_password: user

  pre_tasks:
    - name: Run facter
      ansible.builtin.include_role:
        name: ansible-role-facter

    - name: Fill /etc/hosts with hosts entry
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['facter_ipaddress'] }}  {{ item }}"
      loop: "{{ groups['mongodb_instances'] }}"

    - name: Test hosts
      ansible.builtin.debug:
        msg: "{{ hostvars[item]['facter_ipaddress'] }}  {{ item }}"
      loop: "{{ groups['mongodb_instances'] }}"

  roles:
    - {role: mongodb_install}
    - {role: mongodb_replicaset, when: groups.mongodb_instances.index(inventory_hostname) == 0}
