---
- name: Ensure dbpath directory
  ansible.builtin.file:
    path: "{{ mongodb_storage_dbpath }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    setype: 'mongod_var_lib_t'
    recurse: true
    follow: true

- name: Configure mongodb
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify:
    - Mongodb restart
    - Wait when mongodb is started

- name: Flush all handlers at this point
  ansible.builtin.meta: flush_handlers
