---
- name: Converge
  hosts: all
  become: true
  vars:
    mongodb_net_bindip: 0.0.0.0
    mongodb_storage_dbpath: /var/lib/mongodb/
    mongodb_replication_replset: "rs0"

  pre_tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

  roles:
    - role: mongodb_install
