---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: testserver
    box: geerlingguy/ubuntu2004
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
  lint:
    name: flake8
lint: |
  set -e
  export ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/..
  yamllint .
  ansible-lint
